//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryStore.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public int User_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Email_Id { get; set; }
        public int Group_Id { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tbl_Groups tbl_Groups { get; set; }
    }
}
